## Numpy Examples
reshape, transpose dot, slicing

In [1]:
import numpy as np

Make example data array as numpy.ndarray. Note this array has two rows and 3 columns

In [2]:
a = np.array([[0,1,2],
              [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

Now reshape that to a vector with 6 elements.

In [3]:
a.reshape((6,))


array([0, 1, 2, 3, 4, 5])

Note that the above reshape only has one dimension. Now we reshape it to have two dimensions but one dimesion has a shape of 1.

In [4]:
a.reshape((1,6))

array([[0, 1, 2, 3, 4, 5]])

We can also reshape it to a 3 rows 2 columns.

In [5]:
a.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

While that may have the same shape as the transpose it is not the same.

In [6]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

Now we have an example of the dot product. 

In [7]:
np.dot([1,4,2], [3,1,3])

13

Which can also act like a matrix multiply if done with certain dimensions

In [8]:
b = np.array([[1], [4], [2]])
b

array([[1],
       [4],
       [2]])

In [9]:
c = np.array([[3, 1, 3]])
c

array([[3, 1, 3]])

In [10]:
np.dot(b, c)

array([[ 3,  1,  3],
       [12,  4, 12],
       [ 6,  2,  6]])

Slicing in numpy can be confusing at first but it makes sense if you remember we start indexing at zero and realize we implicitly start at 0 when we slice. The confusing part is that we slice to index 10 but that is the 11th element (0-10) and we only have 10 items in the list. However we don't include the last index so we will get what we expect which is 10 items with indices of 0-9.

In [11]:
x = range(10) # a list of 10 items from 0 to 9
x = list(x)
print(x[:10])
print(x[0:10])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


If you want two slices to be next to each other you use the same number from the end of the first as the beginning of the second

In [12]:
print(x[1:3])
print(x[3:7])
print(x[1:7])

[1, 2]
[3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


When thinking about negative slicing its helpful to realize it will be the same as adding the total size of the array to the negative slicing

In [13]:
print(x[3:-2])   
print(x[3:len(x)-2])    
print(x[3:8])    

[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]
[3, 4, 5, 6, 7]


You can also slice in steps. This slice reads start at index 1 slice to index 7 (not including 7) in steps of 2

In [14]:
print(x[1:7:2])
print(x[1], x[3], x[5])

[1, 3, 5]
1 3 5


See what happens if your last index is not in the step. For example we will step 1,3,5,7,9 but 8 is inbetween 7 and 9 so we include 7 now but not 9.

In [15]:
print(x[1:8:2])
print(x[1], x[3], x[5], x[7])

[1, 3, 5, 7]
1 3 5 7


This is also how you would slice backwards. Since implicitly the step is 1 trying to go backwards will result in an empty slice without giving a -1 for the step

In [16]:
print(x[8:3])
print(x[8:3:-1])

[]
[8, 7, 6, 5, 4]


Remember if you don't do a slice you will just get the single element

In [17]:
print(x[-1])

9


If you want a slice a single element BUT keep it an array

In [18]:
print(x[0:1])
print(x[0])

[0]
0


This gets trickier for the end of the array

In [19]:
print(x[-1:])
print(x[-1])

[9]
9
